### ISSUE TITLE
Child status icon in child list

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#106]
From Claudia:

It would be great if the name list on the homepage would have a little icon in the corresponding colour next to it to indicate the status of a child’s dossier (something like in the screenshot to the right). 
ACTIVE (action within 2-8 months)	green
CURRENT (action within this month)	orange
IN SITU (on-going action required)	blue
RESOLVED		pink
![image](https://user-images.githubusercontent.com/1100062/33530433-377d88f4-d834-11e7-92d9-6c3f1c5ae8ae.png)

**Comment by jdb098** [comment]
scoping work

**Comment by mrmarkwell** [comment]
done
