### ISSUE TITLE
Make Status text field an enum

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#109]
From Claudia:

Status: not a text field but an option to choose between
ACTIVE (action within 2-8 months)	green
CURRENT (action within this month)	orange
IN SITU (on-going action required)	blue
RESOLVED		pink

**Comment by jdb098** [comment]
enum added to backend, making frontend child status options a drop down next

**Comment by jdb098** [comment]
frontend work complete, making pull request
