### ISSUE TITLE
Implement Autosave

### ISSUE THREAD

**Issue by tcase** [mrmarkwell/evergreendb#140]
Follow on from #107 

Implement autosave by giving the user a configurable time between 0 sec and 5 minutes.  Default behavior to be off.

Each separate component would have to get the setting and implement their own timer currently, see this as reference: https://stackoverflow.com/questions/43596477/async-auto-save-in-angular-2-typescript

**Comment by rc2524** [comment]
I confirmed this works, but it will generate a lot of requests. One PUT for each component and each one of those puts triggers a GET for all information from each child. For even a small database (I had 3 children) it would be well over 100 requests every time the timer triggers if I implemented it for all components.

`setInterval(()=>this.saveChild(), 10000)`

**Comment by rc2524** [comment]
Got a method of autosave working for child details in feature/autosave branch. It's not generic so it will require work in each thing that needs saving so I'm asking opinions about the method before I make all the changes.
