### ISSUE TITLE
Include python file static checks as part of TravisCI build

### ISSUE THREAD

**Issue by jdburnet** [mrmarkwell/evergreendb#151]
To avoid nit picky comments in code reviews, static code checks should be included in the TravisCI build. Build should fail if static checkers fail.

For python, there are flake8 and pylint. We'll need to look into including typescript static checkers, I'm not sure what's out there.

**Comment by jdb098** [comment]
Once thing to take into account is that some python functions (those that are part of rest endpoints) are potentially used in typescript code, whose naming conventions don't really align with python. So we're going to have to break the rules somewhere

**Comment by mrmarkwell** [comment]
Not high enough ROI
