### ISSUE TITLE
SQLite doesn't autoincrement IDs

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#159]
https://sqlite.org/autoinc.html
I assumed it did, but since it doesn't, we need to make sure all attachments for a given interaction and the profile picture of a child is deleted when the associated object is deleted. Shouldn't be too hard.

**Comment by mrmarkwell** [comment]
Test case: 
Add an interaction, attach a file, delete interaction, add new interaction. File is still there.

**Comment by jdb098** [comment]
Do we need to turn autoincrement on?

Am I right in thinking this should be done in the rest service? When a child is deleted, look through it's interactions and, if the interaction has attachments, delete them. [There is a deleteInteractionFile method in the rest service](https://github.com/mrmarkwell/evergreendb/blob/d8b54ec6e75ae451170a95c5275649316efc06aa/fss/src/app/rest.service.ts#L136) but it takes a file name. Do we have an easy way to get all interaction file names for a given child?


For child picture I think we can just go through the photo directory an delete all associated with that child's id.

**Comment by mrmarkwell** [comment]
@jdb098 I think we should leave autoincrement off. Your idea is right. The attachments for interaction X are stored in a folder on the backend interactions/X, where X is the interaction id. So finding and deleting them is easy and should probably be handled by the backend (by the delete method in the interaction endpoint). It can just delete the folder with name == interaction_id

Same idea for Child Photo. Probably should be handled by the delete method on the child endpoint.

**Comment by jdb098** [comment]
ok, @mrmarkwell, I'll have to read a bit more in the link from your first comment.

Good point, this seems like a good job for the backend. I've slotted some time to work on this tomorrow, I'll assign it to myself then if no one gets to it before me

**Comment by jdb098** [comment]
well, at least I was able to get the backend running...

- need to remember how to upload interactions
- forgot that entity delete is so generic, need to remember/figure out how to trigger specific events (like looking for a file and deleting it) when certain entities are deleted.

will keep chugging along, may try to sync with you @mrmarkwell offline.
