### ISSUE TITLE
Complete Flask Mega-Tutorial and extract relevant pieces to form base of backend 

### ISSUE THREAD

**Issue by jacksondburnette** [mrmarkwell/evergreendb#16]
- Complete [Flask Mega-Tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) in the [flaskplayground](https://github.com/mrmarkwell/evergreendb/tree/feature/flaskdb/flaskplayground) directory
- When possible, make tweaks to make the content relevant to evergreendb
- Extract relevant content and form base of Flask web app
- be sure to continue to use the unittests developed as part of the tutorial. Make more of them.

**Comment by mrmarkwell** [comment]
Complete
