### ISSUE TITLE
Photo and doc upload not working for Claudia

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#163]
Plan to debug with her on a video chat.

**Comment by rc2524** [comment]
Seems nginx runs as "root" for one process and "apps" for the other, but the queue thing is under "nginx". That's probably the issue.

**Comment by rc2524** [comment]
Possibly fixed, should get Claudia to confirm.

**Comment by rc2524** [comment]
Claudia confirmed fixed
