### ISSUE TITLE
Implement file upload to/download from backend

### ISSUE THREAD

**Issue by jdb098** [mrmarkwell/evergreendb#17]
As noted in @mrmarkwell [comment](https://github.com/mrmarkwell/evergreendb/issues/5#issuecomment-299088986) on #5, there is a requirement to have the ability to upload file to and download files from our web app backend
Use these links as a jumping off point,
http://pythonhosted.org/Flask-Uploads/
http://flask.pocoo.org/docs/0.12/patterns/fileuploads/

**Comment by rc2524** [comment]
This was done a while ago
