### ISSUE TITLE
Reminders tab is flakey. Refresh 10 times and results show up ~3.

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#214]
Go to reminders tab and refresh a bunch. Sometimes it works, sometimes it doesn't.

**Comment by mrmarkwell** [comment]
I bet this has to do with the filtering. Need to check if the date calculation is correct.

**Comment by mrmarkwell** [comment]
Should be fixed with #216

**Comment by rc2524** [comment]
It seems to be fixed with #216 can reopen if not
