### ISSUE TITLE
Sending False instead of false (capital F) as a Json boolean value in POST causes the DB to become unresponsive.

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#22]
To reproduce, in Postman, just change a boolean false to False.

**Comment by rc2524** [comment]
False with a capital F is not legal json syntax, but I guess the DB should handle it better.

**Comment by mrmarkwell** [comment]
This issue causes us to not be able to post "False" from unit tests since we're using the flask test client. I think it might actually be a bug in Flask. All the boolean values in unit tests have to be set to true because of this.
