### ISSUE TITLE
Create flagged notes page

### ISSUE THREAD

**Issue by rc2524** [mrmarkwell/evergreendb#25]
I want to see:
- list/table of flagged notes
  - HTML/javascript interface
  - node.js logic to do REST calls and get data (using a library such as https://www.npmjs.com/package/node-rest-client is probably easiest)
  - have data received show in interface running electron
- Way to get to notes tab of child page.
- Optional: view full note in this page
- Optional: mark flags as complete in this page
- Optional: add generic querying of notes such as only flagged notes for children with specific caregiver (if doing this make story for back end to support well)
- Optional: edit notes in this page

**Comment by mrmarkwell** [comment]
Done and pull request initiated. I did not implement "mark flags complete in this page" or "edit notes in this page", but all the other requirements listed are done.
