### ISSUE TITLE
Research the best way to create an Object-Relational Mapping (ORM) between our database and Flask

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#4]
Research what the best methodology for creating an ORM for our database and Flask objects/classes is. The output of this research user story should be one or more implementation user stories for creating the ORM itself, including all classes and the API we will use to communicate with the database. Don't forget unit testing in the acceptance criteria for these user stories.
- Research SQLAlchemy-Flask as a tool for doing this.

**Comment by tcase** [comment]
I guess I'll take this one :D

**Comment by tcase** [comment]
I think this might make more sense for whoever is setting up the backend to own.  I have done some research but the ORM portion is pretty basic
