### ISSUE TITLE
PUT on child_medication always gives error unless start date is provided

### ISSUE THREAD

**Issue by rc2524** [mrmarkwell/evergreendb#41]
#### url/query
`{{api_base_uri}}/entity/child_medication?id=6`  
#### Body
```
{
  "child_medication_end_date": "2016-04-01"
}
```
#### Response
```
{
  "message": {
    "child_medication_start_date": "Date fields should be entered as: YYYY-MM-DD"
  }
}
```
#### Remarks
I'm updating child_medication_end_date, but the message is about child_medication_start_date. This issue does not happen if child_medication_start_date is also provided.

**Comment by mrmarkwell** [comment]
Good catch. Fixed this. It was a bug in the argument parser for child medications.
