### ISSUE TITLE
Add flask_login protection to the flask_admin interface

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#46]
There are instructions on how to do this on the flask_admin page. 

https://flask-admin.readthedocs.io/en/latest/introduction/

https://github.com/flask-admin/Flask-Admin/tree/master/examples/auth-flask-login

@tcase could you make this dream a reality? Anyone should be able to view. If possible, anyone can create and edit, but only admin can delete. If that's tricky, just make it so only admin can create/edit/delete and everyone else is read-only mode.

**Comment by tcase** [comment]
on it
