### ISSUE TITLE
Research Flask

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#5]
The goal of this user story is to research the capabilities of Flask web server and determine what features of Flask we should use for our web server backend. The output of this user story should be one or more implementation user stories for building up the flask backend. Don't forget unit tests in acceptance criteria for implementation user stories.

**Comment by jacksondburnette** [comment]
This issue relates to issue #6 and issue #4. It may make the most sense for them all to be assigned to the same person. I'll assign them to myself by EOD if I feel like they're sufficiently related such that the resultant implementation stories will all be tied together.

**Comment by tcase** [comment]
sounds good @jacksonburnette i just assigned myself to #4 let me know if you want to do them all together

**Comment by jacksondburnette** [comment]
@tcase, having taken a quick look, I think that there are a couple of options for ORMs (i.e. SQLAlchemy or some custom build) and seemingly one, de facto way of using REST in Flask (i.e. Flask-RESTful). So I think it makes sense for you to take #4 and for me to take #6. Does that sound good to you?

**Comment by mrmarkwell** [comment]
Hey Jackson, as part of this task (or maybe part of the ORM task) we should think about how to handle file attachments. I'm thinking that the database can have a mapping of files to children (I think they want that). But the files themselves would just need to be stored on the filesystem. Looks like Flask has some support for user upload/download and storing files on the filesystem:

http://pythonhosted.org/Flask-Uploads/
http://flask.pocoo.org/docs/0.12/patterns/fileuploads/

That part of the data storage won't be in the database so it should be figured out somewhere else.

Thanks,
Matt

**Comment by jacksondburnette** [comment]
Sounds good @mrmarkwell. I think we can make file upload/download part of the implementation stories created as a result of this research story. I'll be sure to include that.

**Comment by jacksondburnette** [comment]
Going back to my comment about lumping #4 and #6 into this task. I think I was wrong. The separation of these three tasks is good. However, I do think the this research task AND at least some of the resultant implementation tasks will need to be completed before any of the implementation tasks associated with #4 or #6 are completed.

I'll try to complete research and make some implementation tasks before mid tomorrow.

**Comment by jacksondburnette** [comment]
organization: https://exploreflask.com/en/latest/organizing.html
db creation tutorial: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world
