### ISSUE TITLE
FSS - Child List component

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#68]
As an FSS staffmember
I want a list of all FSS children
so that I can search, filter, and select children for a more detailed view.

Acceptance Criteria:

- Child list component renders in appropriate layout pane of the app component
- Child list component uses the data service to populate a list of child objects
- List of children is searchable and filterable (?) might want to break this into a different user story.

**Comment by tcase** [comment]
I might as well take this on :)

**Comment by mrmarkwell** [comment]
done!
