### ISSUE TITLE
FSS - Tab component

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#71]
As an FSS Staffmember
I want a tab view
so that I can select the child detail pane that is of interest to me.

Acceptance criteria:
- Tab pane renders in the appropriate location of the app.component.
- All the tabs described in the design requirements doc are included.
- Tabs can just be placeholders for now.

**Comment by rc2524** [comment]
https://material.angular.io/components/tabs/overview

**Comment by jacksondburnette** [comment]
made pull request #73. Need to make stories for each tab's content

**Comment by jacksondburnette** [comment]
merged and user stories created
