### ISSUE TITLE
FSS - Medical Information Tab

### ISSUE THREAD

**Issue by jacksondburnette** [mrmarkwell/evergreendb#75]
As an FSS staffmember I wan to be able to see medical information for a selected child in the Medical Information Tab

Acceptance Criteria:

- medical information is displayed in medical information tab as specified in [FSS Database Spec](https://github.com/mrmarkwell/evergreendb/blob/develop/requirements/1704%20APP%20Database.docx
 "FSS Database Spec")

**Comment by mrmarkwell** [comment]
Closing this based on recent pull request.
