### ISSUE TITLE
FSS - Projected Pathway Tab

### ISSUE THREAD

**Issue by jacksondburnette** [mrmarkwell/evergreendb#76]
As an FSS staffmember I wan to be able to see the projected pathway for a selected child in the Projected Pathway Tab

Acceptance Criteria:

- projected pathway is displayed in projected pathway tab as specified in [FSS Database Spec](https://github.com/mrmarkwell/evergreendb/blob/develop/requirements/1704%20APP%20Database.docx
 "FSS Database Spec")

**Comment by mrmarkwell** [comment]
Mostly done... Need to add a delete button per row.

I'm thinking also that when the steps are grabbed from the backend, they should be sorted, and then the step numbers should be reassigned to be in order starting at 1. That way if step 4 is deleted, it doesn't go from 3 to 5. It would renumber all the steps accordingly each time they are grabbed.

it wouldn't have to save the new numbers right away, just populate the model. Then if the save button is clicked they'd all be updated.

**Comment by mrmarkwell** [comment]
dun
