### ISSUE TITLE
Research Electron

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#8]
Research using Electron for the frontend infrastructure. 
- This research should focus on two things:
    - Support in Electron for using the REST API in the backend (the data layer of the frontend). Both serializing and sending data, and receiving and deserializing data.
    - Support in Electron for basic User Interface elements we will need for the UI.
- Output of this user story should be one or more implementation user stories defining how to use Electron to build our frontend. 
- Document important learnings so others can quickly get up to speed.

**Comment by mrmarkwell** [comment]
This looks useful: 
https://github.com/sindresorhus/awesome-electron
Looks like there are some good boilerplates to get us started quick.
I read this guide and it was interesting:
https://medium.com/developers-writing/building-a-desktop-application-with-electron-204203eeb658
This looks like the official Electron starting point:
https://electron.atom.io/docs/tutorial/quick-start/

Let me know if you need any help with this! I think it would be possible to basically start building the front-end without data from the backend and then merge them together when we're ready.

**Comment by rc2524** [comment]
Install node.js: see https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
Install electron and add it to $PATH: see https://www.npmjs.com/package/electron#installation
Grab and launch https://github.com/electron/electron-quick-start#to-use
Since electron was installed in previous step you can use `electron .` instead of `npm install; npm start` then we only need index.html, main.js, and package.json and not all the other stuff.

**Comment by rc2524** [comment]
Rest won't be a problem http://www.peej.co.uk/articles/rich-user-experience.html

**Comment by bludrgn** [comment]
To install Electron for the Window Users
1. Install node.js (https://nodejs.org/en/)
2. To make sure you have the latest version node.js (Open cmdline as admin and type "npm install npm -g")
3. Now we're going to install electron. (Open cmdline as admin and type "npm install -g electron")
4. To run electron. (Open cmdline as admin and type "electron")

**Comment by rc2524** [comment]
Looks like ui elements won't be a problem either with many widget libraries to choose from. Sourcing libraries does require some workarounds, but it seems to work fine with them. I haven't looked at any of the server side scripting stuff yet or electron specific file tasks that we could use for attachments.

Work around for loading libs in html (jquery & jquery-ui in this example):
`<!-- Insert this line above script imports  -->`
`<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>`
`<!-- normal script imports etc  -->`
`<script src="scripts/jquery.min.js"></script>`
`<script src="scripts/jquery-ui.min.js"></script>`
`<!-- Insert this line after script imports -->`
`<script>if (window.module) module = window.module;</script>`

**Comment by bludrgn** [comment]
Dang, I wish I read this comment before doing research myself. I found that this piece of code also works.
<script src="scripts/jquery-3.2.1.min.js" onload="window.$ = window.jQuery = module.exports;"></script>
