### ISSUE TITLE
FSS - Child info birthday picker shows date wrong

### ISSUE THREAD

**Issue by rc2524** [mrmarkwell/evergreendb#82]
Shows date format wrong and sometimes shows wrong date entirely.
Date format: here is how to do it, but when I tried it the "provide: MD_DATE_FORMATS" caused an error for me. https://stackoverflow.com/questions/44452966/angular-2-material-2-datepicker-date-format
Wrong date: This is likely because feeding a string as the input of ngmodel where it seems to try to convert it on its own using different time zone or something.

**Comment by mrmarkwell** [comment]
Fixed.

**Comment by mrmarkwell** [comment]
not fixed

**Comment by mrmarkwell** [comment]
updated but the format isn't right yet.
