### ISSUE TITLE
FSS - Make select boxes slect when typing on keyboard

### ISSUE THREAD

**Issue by rc2524** [mrmarkwell/evergreendb#83]
Updating to latest material might work angular/material2#2668
If not either decide to live without or use material auto complete.

(example if the list has Alice, Bob, Bill, Charlie, pressing "b" would move to Bob and pressing "b" again or pressing "bi" quickly would go to bill like a regular html select box does)

**Comment by mrmarkwell** [comment]
the boxes now slect


**slect**
