### ISSUE TITLE
Wireframe of the UI

### ISSUE THREAD

**Issue by mrmarkwell** [mrmarkwell/evergreendb#9]
Use some free wireframing tool to make a wireframe of the UI. This should include all tabs/pages and user interaction elements (buttons, dropdowns, etc.).
- May want to pull in an expert to help or give feedback on this (Zach, Sarah, or Kevin?)

**Comment by bludrgn** [comment]
Does anyone have Zach, Sarah, Kevin's phone number? Can someone who has a close relationship with them ask if they would be down to provide ideas? I can get started on the web development but I need something to base it off of. I'm a horrible designer :P

**Comment by mrmarkwell** [comment]
I think it would be good to start with a free wireframing tool and get feedback from people who know better once we have a prototype.
Maybe try using this: http://pencil.evolus.vn/
